### ISSUE TITLE
Dimensioning Lines

### ISSUE THREAD

**Issue by mattvlaw** [hrc2da/chopshop#6]
CAD-like lines for length and width

**Comment by Pdbz199** [comment]
I think this is done, but not sure if it's exactly what we want.

**Comment by mattvlaw** [comment]
Is it pushed?

**Comment by Pdbz199** [comment]
Cool

**Comment by mattvlaw** [comment]
I opened a PR for it, if you want to check it out. I think a lot of the conflicts are probably editor-enforced styling. Can you upload a screenshot if we can't get the netlify preview working?

**Comment by mattvlaw** [comment]
https://github.com/hrc2da/chopshop/pull/10

**Comment by Pdbz199** [comment]
Just put the screenshot on the PR
