### ISSUE TITLE
Viz Icon for Weight

### ISSUE THREAD

**Issue by mattvlaw** [hrc2da/chopshop#8]
visualize the changes in weight (in the workspace)

**Comment by Pdbz199** [comment]
Would this be like a polygon drawing of a spring type thing that just gets closer to the base as weight increases?

**Comment by Pdbz199** [comment]
Check it out in the visual branch. I think it's like what we wanted. I'm not sure it can represent weight on its own since people might not know what it is right away. Let me know what you think.
